lynt_headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; rv:128.0) Gecko/20100101 Firefox/128.0",
    "Accept": "*/*",
    "Accept-Language": "en-US,en;q=0.5",
    "Referer": "https://lyntr.com/api/lynt",
    "Origin": "https://lyntr.com",
    "DNT": "1",
    "Connection": "keep-alive",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-origin",
    "Sec-GPC": "1",
}
like_lynt_headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; rv:128.0) Gecko/20100101 Firefox/128.0',
    'Accept': '*/*',
    'Accept-Language': 'en-US,en;q=0.5',
    # 'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Referer': 'https://lyntr.com/api/likelynt',
    'Content-Type': 'text/plain;charset=UTF-8',
    'Origin': 'https://lyntr.com',
    'DNT': '1',
    'Alt-Used': 'lyntr.com',
    'Connection': 'keep-alive',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-GPC': '1',
    'Priority': 'u=0',
    # Requests doesn't support trailers
    # 'TE': 'trailers',
}
delete_lynt_headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; rv:128.0) Gecko/20100101 Firefox/128.0',
    'Accept': '*/*',
    'Accept-Language': 'en-US,en;q=0.5',
    # 'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Referer': 'https://lyntr.com/api/lynt?id=9037266491583488',
    'Origin': 'https://lyntr.com',
    'DNT': '1',
    'Alt-Used': 'lyntr.com',
    'Connection': 'keep-alive',
    # 'Cookie': '_TOKEN__DO_NOT_SHARE=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI4NDQ5NTMxMTMxNjQ5MDI0In0.Y9c4HEiGFsWyGkYyvIaXRotSBIZZCFBjs-5OuPTN_mE; temp-discord-token=it89S6FB76SwnFG4YV5ZNfFsNaHo8f; cf_clearance=f77ned0v6Y4aCZ1R9Vx9GSOXIG9XpdjFqFRcYFFVzFY-1723023657-1.0.1.1-Ox5DDG6BMn690ZNvssesWh3K7yLbmv8jzEnRytnDLY5wd86k9kx4nRFCrlGdCPeyDZQqEGb4K7xPmrx9gM2rzw',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-GPC': '1',
    'Priority': 'u=0',
    # Requests doesn't support trailers
    # 'TE': 'trailers',
}
comment_lynt_headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; rv:128.0) Gecko/20100101 Firefox/128.0',
    'Accept': '*/*',
    'Accept-Language': 'en-US,en;q=0.5',
    # 'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Referer': 'https://lyntr.com/api/comment',
    'Content-Type': 'text/plain;charset=UTF-8',
    'Origin': 'https://lyntr.com',
    'DNT': '1',
    'Alt-Used': 'lyntr.com',
    'Connection': 'keep-alive',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-GPC': '1',
    'Priority': 'u=0',
    # Requests doesn't support trailers
    # 'TE': 'trailers',
}
get_lynt_headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; rv:128.0) Gecko/20100101 Firefox/128.0',
    'Accept': '*/*',
    'Accept-Language': 'en-US,en;q=0.5',
    # 'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Referer': 'https://lyntr.com/api/lynt',
    'DNT': '1',
    'Alt-Used': 'lyntr.com',
    'Connection': 'keep-alive',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-GPC': '1',
    'Priority': 'u=0',
    # Requests doesn't support trailers
    # 'TE': 'trailers',
}
profile_headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; rv:128.0) Gecko/20100101 Firefox/128.0',
    'Accept': '*/*',
    'Accept-Language': 'en-US,en;q=0.5',
    # 'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Referer': 'https://lyntr.com/api/profile',
    'DNT': '1',
    'Connection': 'keep-alive',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-GPC': '1',
    'Priority': 'u=4',
    # Requests doesn't support trailers
    # 'TE': 'trailers',
}
